services: docker

language: ruby
rvm:
  - 2.3.3
cache: bundler

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
  - .ci/build.sh
  # https://github.com/coala/coala-bears/issues/1037
  - >
    if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
      sed -i.bak '/bears = GitCommitBear/d' .coafile
    fi
  - docker run -v=$(pwd):/app --workdir=/app coala/base coala --ci

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # Speeds installation of html-proofer

# Route your build to the container-based infrastructure for a faster build
sudo: false
