language: ruby
rvm:
  - 2.3.3
cache: bundler

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: .ci/build.sh

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # Speeds installation of html-proofer

# Route your build to the container-based infrastructure for a faster build
sudo: false
